#!/bin/sh
# $Id$

set -e

# Create the spool lock file on package installation since krb5-sync-backend
# requires that it exist.
if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ] ; then
    if [ ! -f /var/spool/krb5-sync/.lock ] ; then
        touch /var/spool/krb5-sync/.lock
        chmod 600 /var/spool/krb5-sync/.lock
    fi
fi

# Restart kadmind whenever the plugin is changed.
if [ -x "`which invoke-rc.d 2>/dev/null`" ] && [ -x /usr/sbin/kadmind ] ; then
    invoke-rc.d krb5-admin-server start || exit $?
else
    /etc/init.d/krb5-admin-server start || exit $?
fi

#DEBHELPER#

exit 0
