#!/bin/sh
# $Id$
#
# Create the spool lock file on package installation since krb5-sync-backend
# requires that it exist.

set -e

if [ "$1" = "configure" ] && [ -z "$2" ] ; then
    if [ ! -f /var/spool/krb5-sync/.lock ] ; then
        touch /var/spool/krb5-sync/.lock
        chmod 600 /var/spool/krb5-sync/.lock
    fi
fi

#DEBHELPER#

exit 0
